export const LOGIN_USERNAME_PASSWORD_REQUEST =
  "LOGIN_USERNAME_PASSWORD_REQUEST";
export const LOGIN_USERNAME_PASSWORD_SUCCESS =
  "LOGIN_USERNAME_PASSWORD_SUCCESS";
export const LOGIN_USERNAME_PASSWORD_FAILURE =
  "LOGIN_USERNAME_PASSWORD_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const LOGOUT = "LOGOUT";

export const UNAUTHORIZED = "UNAUTHORIZED";

export const FETCH_PROFILES_REQUEST = "FETCH_PROFILES_REQUEST";
export const FETCH_PROFILES_SUCCESS = "FETCH_PROFILES_SUCCESS";
export const FETCH_PROFILES_FAILURE = "FETCH_PROFILES_FAILURE";
