export const LOGIN_USERNAME_PASSWORD_REQUEST =
  "LOGIN_USERNAME_PASSWORD_REQUEST";
export const LOGIN_USERNAME_PASSWORD_SUCCESS =
  "LOGIN_USERNAME_PASSWORD_SUCCESS";
export const LOGIN_USERNAME_PASSWORD_FAILURE =
  "LOGIN_USERNAME_PASSWORD_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const LOGIN_FORGOT_PASSWORD_SUCCESS = "LOGIN_FORGOT_PASSWORD_SUCCESS";
export const LOGIN_FORGOT_PASSWORD_FAILURE = "LOGIN_FORGOT_PASSWORD_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const LOGOUT = "LOGOUT";

export const UNAUTHORIZED = "UNAUTHORIZED";

export const FETCH_PROFILES_REQUEST = "FETCH_PROFILES_REQUEST";
export const FETCH_PROFILES_SUCCESS = "FETCH_PROFILES_SUCCESS";
export const FETCH_PROFILES_FAILURE = "FETCH_PROFILES_FAILURE";

export const FETCH_FAVOURITES_REQUEST = "FETCH_FAVOURITES_REQUEST";
export const FETCH_FAVOURITES_SUCCESS = "FETCH_FAVOURITES_SUCCESS";
export const FETCH_FAVOURITES_FAILURE = "FETCH_FAVOURITES_FAILURE";

export const ADD_FAVOURITES_REQUEST = "ADD_FAVOURITES_REQUEST";
export const ADD_FAVOURITES_SUCCESS = "ADD_FAVOURITES_SUCCESS";
export const ADD_FAVOURITES_FAILURE = "ADD_FAVOURITES_FAILURE";

export const REMOVE_FAVOURITES_REQUEST = "REMOVE_FAVOURITES_REQUEST";
export const REMOVE_FAVOURITES_SUCCESS = "REMOVE_FAVOURITES_SUCCESS";
export const REMOVE_FAVOURITES_FAILURE = "REMOVE_FAVOURITES_FAILURE";
